FROM node:18 AS build

WORKDIR /app

COPY packages/client/package.json packages/client/pnpm-lock.yaml ./client/

RUN npm i -g pnpm

RUN cd client/ && pnpm i

COPY packages/client/ client/

COPY packages/server/ server/

RUN cd server/ && pnpm i

RUN cd client/ && npm run build

FROM nginx:alpine

COPY --from=build /app/client/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
