FROM node:18

WORKDIR /app

COPY packages/server/package.json .

COPY packages/server/pnpm-lock.yaml .

RUN npm i -g pnpm 

RUN pnpm i

COPY packages/server .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
